import sys, pathlib
# Ensure repo root is on sys.path so 'common' and project packages import correctly
repo_root = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(repo_root))
# Also add the project src for convenience
sys.path.insert(0, str((repo_root / 'projects' / '05_terraform_drift_detector' / 'src').resolve()))
from tools.diff_tools import compare_resources_raw

raw = '{"cloud_resources":{"resource_type":"aws_instance","resources":[{"id":"i-0dcbe8a32d59bbff8","type":"aws_instance","name":"drift-detector-test-instance","tags":{"Name":"drift-detector-test-instance","Project":"drift-detector-demo","ManagedBy":"terraform","Owner":"test-user"},"instance_type":"t2.micro","ami":"ami-09ed39e30153c3bf9","availability_zone":"ap-south-1b","vpc_security_group_ids":["sg-00a12d0fe8a095a43"],"attributes":{"id":"i-0dcbe8a32d59bbff8","instance_type":"t2.micro","ami":"ami-09ed39e30153c3bf9","availability_zone":"ap-south-1b","vpc_security_group_ids":["sg-00a12d0fe8a095a43"],"tags":{"Name":"drift-detector-test-instance","Project":"drift-detector-demo","ManagedBy":"terraform","Owner":"test-user"}}}]},"payload":[{"type":"aws_ssm_parameter","name":"amazon_linux_2023_ami","id":"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64","tags":{},"attributes":{"id":"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64","tags":{}}},{"type":"aws_instance","name":"drift_test","id":"i-0dcbe8a32d59bbff8","tags":{"Environment":"production","ManagedBy":"terraform","Name":"drift-detector-test-instance","Owner":"test-user","Project":"drift-detector-demo"},"attributes":{"id":"i-0dcbe8a32d59bbff8","tags":{"Environment":"production","ManagedBy":"terraform","Name":"drift-detector-test-instance","Owner":"test-user","Project":"drift-detector-demo"},"instance_type":"t2.micro","ami":"ami-09ed39e30153c3bf9","availability_zone":"ap-south-1b","vpc_security_group_ids":["sg-00a12d0fe8a095a43"]}}],"state_resources":[{"type":"aws_ssm_parameter","name":"amazon_linux_2023_ami","id":"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64","tags":{},"attributes":{"id":"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64","tags":{}}},{"type":"aws_instance","name":"drift_test","id":"i-0dcbe8a32d59bbff8","tags":{"Environment":"production","ManagedBy":"terraform","Name":"drift-detector-test-instance","Owner":"test-user","Project":"drift-detector-demo"},"attributes":{"id":"i-0dcbe8a32d59bbff8","tags":{"Environment":"production","ManagedBy":"terraform","Name":"drift-detector-test-instance","Owner":"test-user","Project":"drift-detector-demo"},"instance_type":"t2.micro","ami":"ami-09ed39e30153c3bf9","availability_zone":"ap-south-1b","vpc_security_group_ids":["sg-00a12d0fe8a095a43"]}}]}'

out = compare_resources_raw.func(raw=raw)
print(out)
